// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtkmAjOF1x67Iy2V6Ntw8KGq0t5Bcd36Q',
    appId: '1:159584771707:web:6b215c858b9d50b6cd8cde',
    messagingSenderId: '159584771707',
    projectId: 'notia-b47bc',
    authDomain: 'notia-b47bc.firebaseapp.com',
    storageBucket: 'notia-b47bc.firebasestorage.app',
    measurementId: 'G-FB81F3FG3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApnbtLtYJN_WLaI-yuyY3Qc-f3cYQ0Iz4',
    appId: '1:159584771707:android:ad9a5a02f4b9789ecd8cde',
    messagingSenderId: '159584771707',
    projectId: 'notia-b47bc',
    storageBucket: 'notia-b47bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-uW8wPEVe4ArUrKII4S8cwg3NN6IJKe4',
    appId: '1:159584771707:ios:3c22b1aa9e4abf09cd8cde',
    messagingSenderId: '159584771707',
    projectId: 'notia-b47bc',
    storageBucket: 'notia-b47bc.firebasestorage.app',
    iosClientId: '159584771707-kjccsme2njtod52tdkfqkc3ake1masae.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
